### ISSUE TITLE
JRs 您好,您还在虎扑工作吗?

### ISSUE THREAD

**Issue by wh-Coder** [nevergiveup-j/react-native-hupu#1]
我很想加入虎扑, 想和您聊聊

**Comment by nevergiveup-j** [comment]
你好，在的。你需要面试什么岗位

**Comment by wh-Coder** [comment]
前端， 想了解下虎扑对前端的需求，目前我开始了一个高仿虎扑的项目，[点我](https://github.com/wh-Coder/hupuIMI) ，水平等各方面可能还在初级阶段，希望能够得到一些建议，如果能加入虎扑成长就最好不过了

**Comment by nevergiveup-j** [comment]
感谢对虎扑支持，目前招聘需求是高级的。暂时初级的岗位

**Comment by wh-Coder** [comment]
好吧，如果有岗位需求，希望您能推荐一下，时刻准备着
